### ISSUE TITLE
Phone > Developers: the text in "Space for your content to shine" is wrapping around the heading

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#100]

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;hb11nnxl&#x2F;715-phone-section-issues"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Phone section issues</a>

**Comment by grahambancroft** [comment]
Fixed
