### ISSUE TITLE
Add left and right pulls

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/ubuntu-vanilla-theme#11]
Please add and maybe rename the pixel value pulls classes. Here is the Sass for the classes: 
http://paste.ubuntu.com/11729795/

**Comment by yaili** [comment]
@anthonydillon is this still relevant?

**Comment by barrymcgee** [comment]
This theme is no longer supported, please use [Vanilla Framework](https://github.com/vanilla-framework) directly instead.
