### ISSUE TITLE
Management > Overview: row quote issues

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#113]
- [x] there is a space missing before the closing quotation mark
- [ ] the cite style doesn't match the pattern: it's usually italicised
- [ ] the link should probably be in another line below cite
- [ ] same happens in both row quotes

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;JnPorRtR&#x2F;636-management-overview-row-quote-issues"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Management &gt; Overview: row quote issues</a>

**Comment by grahambancroft** [comment]
Fixed

**Comment by magdalena-mirowicz** [comment]
These points are still valid:

 the cite style doesn't match the pattern: it's usually italicised

 the link should probably be in another line below cite

 same happens in both row quotes

**Comment by yaili** [comment]
@grahambancroft can you look into this?
