### ISSUE TITLE
Management > Overview: missing image in ROI row

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#114]

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;c9ms2BYx&#x2F;637-management-overview-missing-image-in-roi-row"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Management &gt; Overview: missing image in ROI row</a>

**Comment by grahambancroft** [comment]
Fixed
