### ISSUE TITLE
Management > Landscape features: tabs pattern will need updating

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#115]
To be discussed.

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;enRUxRdd&#x2F;638-management-landscape-features-tabs-pattern-will-need-updating"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Management &gt; Landscape features: tabs pattern will need updating</a>

**Comment by grahambancroft** [comment]
We’ve removed the tabs for now
