### ISSUE TITLE
Management > Working with Landscape: hero missing image

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#116]

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;F1oVxJYn&#x2F;639-management-working-with-landscape-hero-missing-image"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Management &gt; Working with Landscape: hero missing image</a>

**Comment by grahambancroft** [comment]
Fixed
