### ISSUE TITLE
Management > Compliance: the images are overflowing the page

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#117]

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;fbFLC57I&#x2F;640-management-compliance-the-images-are-overflowing-the-page"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Management &gt; Compliance: the images are overflowing the page</a>

**Comment by grahambancroft** [comment]
Fixed
