### ISSUE TITLE
Management > UA: the spacing in the hero is incorrect

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#118]

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;QU4bwh2V&#x2F;641-management-ua-the-spacing-in-the-hero-is-incorrect"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Management &gt; UA: the spacing in the hero is incorrect</a>

**Comment by grahambancroft** [comment]
Fixed
