### ISSUE TITLE
Management > UA: the boxes in second row are doubled

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#119]

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;AV6sDj6p&#x2F;642-management-ua-the-boxes-in-second-row-are-doubled"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Management &gt; UA: the boxes in second row are doubled</a>

**Comment by grahambancroft** [comment]
Fixed
