### ISSUE TITLE
Home: the image in "Buy a managed cloud" is duplicated

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#131]
It is showing a large and small image on top

**Comment by grahambancroft** [comment]
Fixed

**Comment by yaili** [comment]
This is what I see:
![screen shot 2016-04-10 at 10 07 27](https://cloud.githubusercontent.com/assets/223966/14409053/0d64f7a6-ff04-11e5-8c7e-c4135c15f6af.png)

**Comment by magdalena-mirowicz** [comment]
fix confirmed
