### ISSUE TITLE
Desktop > Features: the hero image is too close to the top edge of row

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#139]
The same happens in developers and enterprise pages.

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;XY1tAb9i&#x2F;658-desktop-features-the-hero-image-is-too-close-to-the-top-edge-of-row"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Desktop &gt; Features: the hero image is too close to the top edge of row</a>

**Comment by grahambancroft** [comment]
Fixed
