### ISSUE TITLE
Management > ROI: the row with the large numbers doesn't have the same top padding as other rows

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#141]

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;g9MU9ApQ&#x2F;633-management-roi-the-row-with-the-large-numbers-doesn-t-have-the-same-top-padding-as-other-rows"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Management &gt; ROI: the row with the large numbers doesn&#39;t have the same top padding as other rows</a>
