### ISSUE TITLE
incorrect path to "node_modules"

### ISSUE THREAD

**Issue by michaldev** [ubuntudesign/ubuntu-vanilla-theme#150]
`@import '../node_modules/vanilla-framework/scss/vanilla';`
According to the directory 'node_modules' should be in the 'css'.

It should look like this:
`@import '../../../node_modules/vanilla-framework/scss/vanilla';`

![zrzut ekranu 2016-04-03 o 10 55 15](https://cloud.githubusercontent.com/assets/5132385/14231624/952a5b88-f98a-11e5-919e-af7577a26271.png)

**Comment by anthonydillon** [comment]
Hi @isMichael,

The prefixed `../` jumps back a directory and therefore leaves is looking for the node_modules folder in the ubuntu-vanilla-theme folder. Which is where it should be found.

Are you experiencing an error?

**Comment by nottrobin** [comment]
This might be because you're installing node modules with `npm` version 3. It only works with `npm` version 2 or lower (something we should really fix).

**Comment by deshack** [comment]
This has been fixed with #179, but is not included in v0.0.34. With code from branch master and a couple of changes in gulp/compass/whatever, it works.

**Comment by yaili** [comment]
@nottrobin @anthonydillon is this issue closed?

**Comment by barrymcgee** [comment]
This theme is no longer supported, please use [Vanilla Framework](https://github.com/vanilla-framework) directly instead.
