### ISSUE TITLE
Cloud > Public cloud: link not working

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#155]

**Comment by nottrobin** [comment]
Fixed in https://github.com/ubuntudesign/www.ubuntu.com/pull/132

**Comment by yaili** [comment]
This isn't working yet.

**Comment by nottrobin** [comment]
Sorry @yaili Try again now?

http://www.ubuntu.com-master.demo.haus/cloud/public-cloud

If doesn't work try in an incognito window?

**Comment by yaili** [comment]
Now it works. Thanks.
