### ISSUE TITLE
Ticks are too dark

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#168]
See #22 for correct asset

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;jaADfvRV&#x2F;755-ticks-are-too-dark"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ticks are too dark</a>

**Comment by grahambancroft** [comment]
Fixed
