### ISSUE TITLE
How to correctly compile vanilla framework and the Ubuntu theme?

### ISSUE THREAD

**Issue by michaldev** [ubuntudesign/ubuntu-vanilla-theme#181]
How to correctly compile vanilla framework and the Ubuntu theme?

I tried this:

```
git clone https://github.com/ubuntudesign/ubuntu-vanilla-theme
cd ubuntu-vanilla-theme
./.install_depedencies.sh
npm install
gulp sass
```

I built a correctly css files, but do not run some components. e.g.
![zrzut ekranu 2016-05-21 o 10 11 56](https://cloud.githubusercontent.com/assets/5132385/15447255/a9759e18-1f3c-11e6-8abd-c1c3b5b7b887.png)
![zrzut ekranu 2016-05-21 o 10 12 50](https://cloud.githubusercontent.com/assets/5132385/15447254/a975113c-1f3c-11e6-9cae-744d3fa120c8.png)
![zrzut ekranu 2016-05-21 o 10 22 41](https://cloud.githubusercontent.com/assets/5132385/15447286/0b7511b0-1f3e-11e6-9018-41c8720cfba0.png)
![zrzut ekranu 2016-05-21 o 10 22 56 1](https://cloud.githubusercontent.com/assets/5132385/15447287/0b767f00-1f3e-11e6-84fb-45dc76dc65c1.png)

**Comment by anthonydillon** [comment]
To work on the theme you should do the following steps
```
git clone https://github.com/ubuntudesign/ubuntu-vanilla-theme
cd ubuntu-vanilla-theme
npm install
gulp build
```

Then you can open the pattern demo in `demo/index.html`. This raises the point that we should add a hacking document to the repo to help people develop the themes.

**Comment by bottinbio** [comment]
this code fails on ubuntu 16.04

**Comment by barrymcgee** [comment]
This theme is no longer supported, please use [Vanilla Framework](https://github.com/vanilla-framework) directly instead.
