### ISSUE TITLE
Input & button height

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/ubuntu-vanilla-theme#182]
I hope this is the right place to file this.

In the newsletter row on [the devices page](https://www.ubuntu.com/phone/devices), the input field and submit button are placed side-by-side:

![newsletter form](https://assets.ubuntu.com/v1/0bcded76-newsletter.png)

In Chrome, the input field is 42px high (with the border) and the button is 40px, meaning the bottom of the submit button doesn't quite align with the bottom of the input, by 2 px. I assume this is unintentional, and the submit should also be 42px high?

**Comment by barrymcgee** [comment]
This theme is no longer supported, please use [Vanilla Framework](https://github.com/vanilla-framework) directly instead.

**Comment by nottrobin** [comment]
@barrymcgee This was a genuine issue with vanilla framework - that buttons weren't the same height as fields. I'm not sure if it already exists on one of the repositories, or if it's maybe been already done? But it shouldn't be forgotten - it's important for build.snapcraft.io at least, probably for other projects.

**Comment by barrymcgee** [comment]
@nottrobin In Vanilla 1.6.1, both inputs and buttons are both  42px high - [see live demo](https://codepen.io/barrymcgee/full/BwbwGR)

<img width="1183" alt="screen shot 2017-10-20 at 14 24 20" src="https://user-images.githubusercontent.com/505570/31822981-7aeb1728-b5a2-11e7-8f68-e734588f4fa3.png">

**Comment by nottrobin** [comment]
@barrymcgee sweet! Thanks :)
