### ISSUE TITLE
Update autoprefixer

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/ubuntu-vanilla-theme#19]
We should update our autoprefixer version to 2.3.1. To stop this warning while compiling:
`Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead`

**Comment by barrymcgee** [comment]
This theme is no longer supported, please use [Vanilla Framework](https://github.com/vanilla-framework) directly instead.
