### ISSUE TITLE
Update assets to use new Ubuntu orange #E95420

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#22]
Recurring images:
- List tick: https://assets.ubuntu.com/v1/c4b02d61-tick-orange.svg
- External link: https://assets.ubuntu.com/v1/fe01a330-external-link-orange.svg
- 404: https://assets.ubuntu.com/v1/bcdcf2c8-image-404.svg

Pictograms:
- Help https://assets.ubuntu.com/v1/9b170f06-picto-help-orange.svg
  - http://www.ubuntu.com/cloud/openstack/training
  - http://www.ubuntu.com/server/management
  - http://www.ubuntu.com/desktop
  - http://www.ubuntu.com/phone/developers
- Virtualisation https://assets.ubuntu.com/v1/00438906-pictogram-virtualisation.svg
  - http://www.ubuntu.com/cloud/lxd
- Core power https://assets.ubuntu.com/v1/e35b1108-picto-corepower-orange.svg
  - http://www.ubuntu.com/cloud/snappy
- Community https://assets.ubuntu.com/v1/039628d5-picto-community-orange.svg
  - http://www.ubuntu.com/server
  - http://www.ubuntu.com/desktop/developers
- Education https://assets.ubuntu.com/v1/7c8b4a70-picto-education-orange.svg
  - http://www.ubuntu.com/desktop
- Projects we love https://assets.ubuntu.com/v1/095a11c1-picto-projectswelove-orange.svg
  - http://www.ubuntu.com/desktop/features
  - http://www.ubuntu.com/desktop/enterprise
  - http://www.ubuntu.com/desktop/education
  - http://www.ubuntu.com/desktop/government
  - http://www.ubuntu.com/desktop/partners
  - http://www.ubuntu.com/phone (twice)
  - http://www.ubuntu.com/phone/features
  - http://www.ubuntu.com/phone/devices
  - http://www.ubuntu.com/phone/partners
  - http://www.ubuntu.com/tablet/operators-and-oems
  - http://www.ubuntu.com/tablet
  - http://www.ubuntu.com/tablet/app-ecosystem
- Upgrade https://assets.ubuntu.com/v1/423e9265-picto-upgrade-orange.svg
  - http://www.ubuntu.com/desktop/partners
- Server https://assets.ubuntu.com/v1/bb7440f9-picto-server-orange.svg
  - http://www.ubuntu.com/management
- Cloud https://assets.ubuntu.com/v1/b2015716-picto-cloud-orange.svg
  - http://www.ubuntu.com/management
- Desktop https://assets.ubuntu.com/v1/cb9ee959-picto-desktop-orange.svg
  - http://www.ubuntu.com/management/ubuntu-advantage (twice)
- Download https://assets.ubuntu.com/v1/e9ae5806-picto-download-orange.svg
  - http://www.ubuntu.com/download/
- Circle of friends https://assets.ubuntu.com/v1/c5cb0f8e-picto-ubuntu.svg
  - http://www.ubuntu.com/download/desktop
- Ubuntu Kylin https://assets.ubuntu.com/v1/5828bf44-picto-ubuntukylin.svg
  - http://www.ubuntu.com/download
  - http://www.ubuntu.com/download/desktop

Illustrations:
- Cloud hero https://assets.ubuntu.com/v1/1c786630-image-cloud.svg
  - http://www.ubuntu.com/cloud/partners
- Tender https://assets.ubuntu.com/v1/1ae6ed1d-image-tenders-with-ubuntu.svg
  - http://www.ubuntu.com/desktop/partners
- Tablet convergence https://assets.ubuntu.com/v1/753e4f2f-image-tablet-converged.svg
  - http://www.ubuntu.com/tablet
  - http://www.ubuntu.com/tablet/operators-and-oems
- Start creating your app now https://assets.ubuntu.com/v1/197ba2e3-image-tablet-startcreatingyourappnow.svg
  - http://www.ubuntu.com/tablet/app-ecosystem
- A global brand https://assets.ubuntu.com/v1/1dac0f5f-image-tablet-globalbrand.svg
  - http://www.ubuntu.com/tablet/operators-and-oems
- Support and management tools https://assets.ubuntu.com/v1/11da76f5-image-management.svg
  - http://www.ubuntu.com/management
- Storage hero https://assets.ubuntu.com/v1/c2d50399-storage.svg
  - http://www.ubuntu.com/cloud/openstack/storage
- Public cloud hero https://assets.ubuntu.com/v1/1873dc3c-image-publiccloud.svg
  - http://www.ubuntu.com/cloud/public-cloud

Other assets yet to be edited:
- Ubuntu logo inside cloud http://www.ubuntu.com/cloud/openstack and http://www.ubuntu.com/cloud
- Unity 8 illustration http://www.ubuntu.com/desktop/ubuntu-kylin
- Ubuntu CoF in maps http://www.ubuntu.com/desktop/education and http://www.ubuntu.com/desktop/government
- Lock security http://www.ubuntu.com/desktop/government
- Ubuntu Core illustration http://www.ubuntu.com/download

Will not update:
- Graph in http://www.ubuntu.com/desktop/developers (should be CSS)
- LTS release cycle (should be CSS)
  - http://www.ubuntu.com/desktop/enterprise
  - http://www.ubuntu.com/server
- Things (design will change)
- Architecture at the bottom of http://www.ubuntu.com/cloud/snappy (should be CSS)

**Comment by HEXcube** [comment]
@yaili Did Canonical change the orange from #DD4814 to this new #E95420 for all purposes? :open_mouth: But, the [Brand Color Guidelines][brand-color] and [Web Color Palette][web-color] still specifies  #DD4814 as **Ubuntu Orange**. :confused: . Shouldn't this be changed as well?

The first place where I noted the change was on Ubuntu 15.10 _"Wily Werewolf"_'s official logo `werewolf_orange_hex.svg` on [Ubuntu Official Artwork page][ubuntu-artwork]. At first I thought I was a mistake, but then I came across this issue. I couldn't find any other official news or announcement about this change. So, I decided to ask here itself. :innocent: 

[brand-color]: https://design.ubuntu.com/brand/colour-palette "Guidelines for using Ubuntu brand colors"
[web-color]: https://design.ubuntu.com/web/colour "Ubuntu color palette for web"
[ubuntu-artwork]: https://wiki.ubuntu.com/Artwork/Official "Ubuntu Official Artwork Wiki page"

**Comment by yaili** [comment]
@HEXcube you're correct. Going forward we'll be updating the orange to be consistent everywhere. The update to the guidelines documentation and the framework should happen soon. Thanks for pointing this out!

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;8wwsIWR3&#x2F;725-update-assets-to-use-new-ubuntu-orange-e95420"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Update assets to use new Ubuntu orange #E95420</a>

**Comment by grahambancroft** [comment]
Fixed

**Comment by yaili** [comment]
I've only tested random images. But the external link icons in server phone and tablet are not updated.

**Comment by barrymcgee** [comment]
This theme is no longer supported, please use [Vanilla Framework](https://github.com/vanilla-framework) directly instead.
