### ISSUE TITLE
Theme breaks with npm 3.x

### ISSUE THREAD

**Issue by pietroalbini** [ubuntudesign/ubuntu-vanilla-theme#26]
Flat dependencies installation was introduced by default in [npm 3](https://github.com/npm/npm/releases/tag/v3.0.0), which means that, if there aren't any conflicts, every dependency will be installed in the first `node_modules` directory, without any nested `node_modules`, and there is no way to disable this behavior currently.

This means that installing `ubuntu-vanilla-theme` with npm 3 produces the following directory tree:

```
+-- node_modules
  +-- ubuntu-vanilla-theme
  +-- vanilla-framework
```

For reference, npm 2 produces the following tree:

```
+-- node_modules
  +-- ubuntu-vanilla-theme
    +-- node_modules
      +-- vanilla-framework
```

This change breaks the theme because in the `scss/_theme.scss` file, vanilla is included with `../node_modules/vanilla-framework`, which doesn't exists anymore with npm 3.

Because this change can't be disabled by the package in npm 3, the workaround I found is to trick npm 2 to use the npm 3 structure by using the [`peerDependencies`](https://docs.npmjs.com/files/package.json#peerdependencies) directive in the `package.json`, which installs the dependencies specified in it always alongside the theme's package. But because in npm 3 dependencies specified in peerDependencies aren't installed by default, you **also** need to specify them in the usual `dependencies` directive. And finally it's needed to change the import of vanilla to point to `../../node_modules` instead of `../node_modules`.

This approach has two disadvantages: first of all, you need to duplicate the dependencies version, and npm 2 emits a warning everytime you install the package (but it's useless). Instead, the advantage is that you have a package which works the same way in npm 2 and npm 3.

In npm 3 the resulting directory tree is the same, but in npm 2 it's the following one:

```
+-- node_modules
  +-- vanilla-framework
  +-- ubuntu-vanilla-theme
    +-- node_modules
      +-- vanilla-framework
```

This fix is required because npm 3 will be the packaged one in [xenial](http://packages.ubuntu.com/xenial/npm).

**Comment by pietroalbini** [comment]
This should probably be fixed also in the other themes.

**Comment by anthonydillon** [comment]
Thank you very much for taking the time to report this detailed issue.

We are aware of the change in infrastructure for NPM 3 but have not come to
an agreed solution. Ideally the system itself could detect structure used
and just work in either case.

I wonder if a configuration variable in the main scss file would be enough
to update the import path. The default could be set to NPM 2 but if `npm3`
is set to true it would using the flat folder structure to import Vanilla.

Another solution could be to have NPM or gulp update a variable to act as
the path to the framework.

If anyone else has any other solutions it would be appreciated.

**Comment by pietroalbini** [comment]
>  I wonder if a configuration variable in the main scss file would be enough to update the import path. The default could be set to NPM 2 but if `npm3` is set to true it would using the flat folder structure to import Vanilla.

> Another solution could be to have NPM or gulp update a variable to act as the path to the framework.

This won't work, because scss doesn't allow to use variables in the import statements, and neither to wrap the import into an if block, since imports are executed before the rest of the code. I tried to put the imports in an if-else block, but scss tried to execute both the import statements anyway.

**Comment by pietroalbini** [comment]
By the way, I just found an issue with the approach I proposed: `gulp sass` doesn't work anymore. That's because the new directory structure (which is the only one allowed by NPM 3) isn't the one you get when doing `npm install` into the repository, but the old we can't use.

Because it's not possible to conditionally import the framework, I came out with this little hack:

* `_theme.scss` is moved to `_vanilla_theme.scss`, with the framework import removed
* `_theme.scss` imports the framework from `../../node_modules` and then `vanilla-theme`
* `build.scss` import the framework from `../node_modules` and then `vanilla-theme`

This way packages works as before importing `scss/theme`, if you want to import vanilla from a custom location you can then use `.../scss/vanilla-theme`, and `build.scss` works as before.

I'm probably going with this approach for our LoCoTeam theme (which imports this theme which imports vanilla), if you want I can link the source once I finish some little tweaks.

**Comment by pietroalbini** [comment]
My own fix for the problem is available [here](http://code.ubuntu-it.org/ubuntu-it-web/ubuntuit-vanilla-theme).

**Comment by pietroalbini** [comment]
Would be possible to implement a fix for this? [xenial ships with npm@3](http://packages.ubuntu.com/xenial/npm).

**Comment by deshack** [comment]
Well, the solution is quite simple, just use sass import paths.
Using plain paths in sass `@import`s is bad, just don't do that.

I will soon submit a PR, so that you can check if the solution suits your requirements or not.
