### ISSUE TITLE
Consider having 2 types of row padding: tight and spacious

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#47]
I was thinking we should maintain two types of row padding, the old/current one used across most of u.com — "tight" — and the larger one we've used on tablet, Landscape, phone — "spacious". Then we'd have the option depending on what the content requires. Thoughts? @anthonydillon

**Comment by magdalena-mirowicz** [comment]
@yaili can't verify it - please check

**Comment by yaili** [comment]
This will be fixed later based on decision made on patterns workshop.

**Comment by barrymcgee** [comment]
This theme is no longer supported, please use [Vanilla Framework](https://github.com/vanilla-framework) directly instead.
