### ISSUE TITLE
Cloud > LXD: the code block in "Getting started with LXD" should be inheriting Vanilla style

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#51]
There should be an issue in vanilla to update the default code style. @anthonydillon

**Comment by magdalena-mirowicz** [comment]
@yaili can't verify it - please check

**Comment by yaili** [comment]
Hasn't been done yet.

**Comment by WillMoggridge** [comment]
This actually is inheriting vanilla style from what I can see, but vanilla doesn't yet have any real style to its code blocks.

The only entries are here: https://github.com/ubuntudesign/vanilla-framework/blob/01db6f00a1edd3c6c8560ad82d5f5b655914ba99/scss/modules/_typography.scss#L353

**Comment by yaili** [comment]
@WillMoggridge the code block styles for Vanilla are defined here: https://github.com/ubuntudesign/meeting-notes/issues/12

**Comment by magdalena-mirowicz** [comment]
@yaili please review on demo 16.04

**Comment by yaili** [comment]
@magdalena-mirowicz it looks the same
