### ISSUE TITLE
Main nav dropdown shouldn't highlight current page

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#55]

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;jkrCISO8&#x2F;630-main-nav-dropdown-shouldn-t-highlight-current-page"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Main nav dropdown shouldn&#39;t highlight current page</a>

**Comment by grahambancroft** [comment]
Fixed
