### ISSUE TITLE
Server > Overview: missing Insights row before community row at the bottom

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#61]
Is this being added later?

**Comment by yaili** [comment]
If this is a bug, it's missing content, so should be addressed @grahambancroft

**Comment by pmahnke** [comment]
@yaili this isn't a bug, if you have js, but it can't get to the feed (and it can't unless it's live) you don't get the content... look in your console to see the CORS error.

if you don't have javascript, you get a message to visit insights... at the time, I thought this the best options... it is also on the homepage news feed.

**Comment by yaili** [comment]
ok.
