### ISSUE TITLE
The space between breadcrumbs items is not the same

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#62]
Compare with live: the space between a link and the chevron should be the same as between a link and another link

**Comment by yaili** [comment]
Would be good to check this one @grahambancroft

**Comment by yaili** [comment]
@grahambancroft this is probably a bigger issue to fix, but it was added during vanilla release

**Comment by barrymcgee** [comment]
This theme is no longer supported, please use [Vanilla Framework](https://github.com/vanilla-framework) directly instead.
