### ISSUE TITLE
Server > Hyperscale: partners grid boxes don't have equal heights

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#67]

**Comment by grahambancroft** [comment]
Fixed

**Comment by yaili** [comment]
Still don't.

**Comment by magdalena-mirowicz** [comment]
still valid

**Comment by yaili** [comment]
@grahambancroft still an issue

**Comment by yaili** [comment]
@pmahnke @magdalena-mirowicz should this be moved to www.ubuntu.com repo?

**Comment by magdalena-mirowicz** [comment]
@yaili yes, is there a way to move it easily? Or do we need to close and reopen?

**Comment by pmahnke** [comment]
This issue was moved to ubuntudesign/www.ubuntu.com#1325
