### ISSUE TITLE
Server > Hyperscale: please remove the pattern at the bottom of the page

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#68]
Let's do:

h2
six-col with logo cloud   ||   six-col with logo cloud

**Comment by magdalena-mirowicz** [comment]
still valid

**Comment by yaili** [comment]
@grahambancroft instead of using grey logos in that box, we should use the logo cloud. If possible, this pattern should be removed from the CSS. If there is any other instance of it on the site it should be replaced too. Thanks!
