### ISSUE TITLE
Desktop > Developers: closing quotation mark in blockquote missing space before it

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#88]

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;LgaiV3nP&#x2F;657-desktop-developers-closing-quotation-mark-in-blockquote-missing-space-before-it"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Desktop &gt; Developers: closing quotation mark in blockquote missing space before it</a>

**Comment by grahambancroft** [comment]
Fixed
