### ISSUE TITLE
Desktop > China: image in "Youker Assistant" is overflowing container

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#91]
The same issue happens in "Smart Scopes", "Kingsoft WPS Office", "Chinese lunar calendar" and "Kingsoft Kuaipan cloud storage" rows.

**Comment by pmahnke** [comment]
@grahambancroft and @yaili I think I have put in a fix for this https://github.com/ubuntudesign/www.ubuntu.com/pull/286
