### ISSUE TITLE
Phone > Features: the main text block in "Everything you expect…" should be centre vertically aligned

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#95]

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;hb11nnxl&#x2F;715-phone-section-issues"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Phone section issues</a>

**Comment by magdalena-mirowicz** [comment]
still valid

**Comment by yaili** [comment]
@grahambancroft can you look into this one?
