### ISSUE TITLE
Phone > Devices: the lists of features are going over the content container, they should be contained within the grid

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/ubuntu-vanilla-theme#98]

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;hb11nnxl&#x2F;715-phone-section-issues"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Phone section issues</a>

**Comment by magdalena-mirowicz** [comment]
fix confirmed

**Comment by magdalena-mirowicz** [comment]
still an issue

**Comment by magdalena-mirowicz** [comment]
This issue was moved to ubuntudesign/www.ubuntu.com#368
